#!/usr/bin/env bash
# Render MissingPapers.md -> docs/MissingPapers.html.
# Re-run whenever MissingPapers.md changes; the HTML is a derived file.
set -euo pipefail
cd "$(dirname "$0")/.."

body=$(pandoc --from=gfm --to=html MissingPapers.md)

{
cat <<'HEAD'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Dana S. Scott — Missing Papers</title>
<style>
  :root{
    --bg:#faf9f7; --panel:#ffffff; --ink:#1b1a17; --muted:#6b6862;
    --line:#e6e2db; --accent:#7a4d3b; --accent2:#3d5a6c; --chip:#f1ede6;
    --shadow:0 1px 2px rgba(0,0,0,.05),0 4px 16px rgba(0,0,0,.04);
  }
  @media (prefers-color-scheme: dark){
    :root{
      --bg:#171614; --panel:#201e1b; --ink:#eceae5; --muted:#a29d94;
      --line:#33302b; --accent:#d59b82; --accent2:#8fb3c7; --chip:#2a2723;
      --shadow:0 1px 2px rgba(0,0,0,.3),0 6px 22px rgba(0,0,0,.28);
    }
  }
  *{box-sizing:border-box}
  body{
    margin:0 auto; max-width:1000px; padding:32px 20px 64px;
    background:var(--bg); color:var(--ink);
    font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
    -webkit-font-smoothing:antialiased;
  }
  a{color:var(--accent2)}
  h1{font-size:30px; line-height:1.15; margin:0 0 6px; letter-spacing:-.01em}
  h2{font-size:20px; margin:34px 0 10px; padding-top:14px; border-top:1px solid var(--line)}
  blockquote{
    margin:18px 0; padding:14px 18px; background:var(--panel);
    border:1px solid var(--line); border-left:3px solid var(--accent);
    border-radius:10px; box-shadow:var(--shadow);
  }
  blockquote h2{margin:0; padding:0; border:0; font-size:17px}
  table{border-collapse:collapse; width:100%; margin:10px 0 4px; font-size:15px}
  th,td{border:1px solid var(--line); padding:8px 10px; text-align:left; vertical-align:top}
  th{background:var(--chip); font-weight:600}
  td:first-child,th:first-child{width:3em; color:var(--muted); text-align:right}
  code{background:var(--chip); padding:1px 5px; border-radius:5px; font-size:14px}
  ul{padding-left:22px}
  footer{margin-top:44px; padding-top:14px; border-top:1px solid var(--line);
         color:var(--muted); font-size:13px}
</style>
</head>
<body>
HEAD
printf '%s\n' "$body"
cat <<'FOOT'
<footer>
Generated from <code>MissingPapers.md</code> by <code>scripts/build-missing-papers.sh</code> — do not edit this file by hand.
Held/missing state per entry is also browsable in <a href="overviewplusabstracts.html">the bibliography overview</a>.
</footer>
</body>
</html>
FOOT
} > docs/MissingPapers.html

echo "wrote docs/MissingPapers.html ($(wc -c < docs/MissingPapers.html) bytes)"
